### ISSUE TITLE
gettransaction method is missing the category field in response message

### ISSUE THREAD

**Issue by pbca26** [jl777/SuperNET#59]
If possible can you add this field to listtransactions method? It was also omitted.
Also, can you look if you can add transaction value field as well? Right now the only way to get the value is to iterate iterate through satoshis and check for a specific address. It would be convenient if transaction value can be retrieved right away.

**Comment by jl777** [comment]
please provide a specific curl API call that displays the issue. also I can add a value field, but if bitcoind RPC doesnt, then it wont be backward compatible. Having a specific example of how you invoked iguana and a specific JSON that you expected would help a lot. as it is I have to guess what you need

**Comment by pbca26** [comment]
Here are two bitcoind samples. I highlighted missing fields.

curl --url "http://127.0.0.1:8332" --data-binary '{"jsonrpc": "1.0", "method": "listtransactions", "params": [] }' 
{"result":[{"account":"","address":"1G7GjuQx3krot5LYkphcXM4mhnmXi8Er9U","category":"receive","amount":0.00010000,"label":"","vout":0,"confirmations":19,"blockhash":"000000000000000000ad1278df428f8a01a6f4fb0c06ce6a9cdcaf12e164973e","blockindex":1729,"blocktime":1471938431,"txid":"8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c","walletconflicts":[],"time":1471937620,"timereceived":1471937620,"bip125-replaceable":"no"},{"account":"","address":"1G7GjuQx3krot5LYkphcXM4mhnmXi8Er9U",curl --url "http://pbca2696:pbca2696@127.0.0.1:8332" --data-binary '{"jsonrpc": "1.0", "method": "gettransaction", "params": ["8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c"] }' 

output
{"result":{"amount":0.00010000,"confirmations":53,"blockhash":"000000000000000000ad1278df428f8a01a6f4fb0c06ce6a9cdcaf12e164973e","blockindex":1729,"blocktime":1471938431,"txid":"8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c","walletconflicts":[],"time":1471937620,"timereceived":1471937620,"bip125-replaceable":"no","details":[{"account":"","address":"1G7GjuQx3krot5LYkphcXM4mhnmXi8Er9U","category":"receive","amount":0.00010000,"label":"","vout":0}],"hex":"01000000012bc52029f0dc260b8885a4b614a9c28cfff9e975808fa3b09e1bc6f0f507a795010000006a47304402200a21a6ba6c835fc425cdb282b1f35ada5fb3913de05a892fd1c2724e98a7c1490220676e915af65829f9d0c6abb2f0c2242b7c149c097cdfd7d2c7c57318ef0e87f301210261d7d5a53832dab69a3f869511071197c700aae62bafd965b9123ffdfb16eff9ffffffff0210270000000000001976a914a5b985795647ae4e0215054149eb03cd27b7671f88aca2ea0e00000000001976a91477b906930f44cacbc0216c1cb24400aefe06410f88ac00000000"},"error":null,"id":null}
curl --url "http://pbca2696:pbca2696@127.0.0.1:8332" --data-binary '{"jsonrpc": "1.0", "method": "gettransaction", "params": ["8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c"] }' 
{"result":{"amount":0.00010000,"confirmations":53,"blockhash":"000000000000000000ad1278df428f8a01a6f4fb0c06ce6a9cdcaf12e164973e","blockindex":1729,"blocktime":1471938431,"txid":"8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c","walletconflicts":[],"time":1471937620,"timereceived":1471937620,"bip125-replaceable":"no","details":[{"account":"","address":"1G7GjuQx3krot5LYkphcXM4mhnmXi8Er9U","category":"receive","amount":0.00010000,"label":"","vout":0}],"hex":"01000000012bc52029f0dc260b8885a4b614a9c28cfff9e975808fa3b09e1bc6f0f507a795010000006a47304402200a21a6ba6c835fc425cdb282b1f35ada5fb3913de05a892fd1c2724e98a7c1490220676e915af65829f9d0c6abb2f0c2242b7c149c097cdfd7d2c7c57318ef0e87f301210261d7d5a53832dab69a3f869511071197c700aae62bafd965b9123ffdfb16eff9ffffffff0210270000000000001976a914a5b985795647ae4e0215054149eb03cd27b7671f88aca2ea0e00000000001976a91477b906930f44cacbc0216c1cb24400aefe06410f88ac00000000"},"error":null,"id":null}
**"category":"receive","amount":0.00010000**,"label":"","vout":0,"confirmations":19,"blockhash":"000000000000000000ad1278df428f8a01a6f4fb0c06ce6a9cdcaf12e164973e","blockindex":2148,"blocktime":1471938431,"txid":"b9ee4a70a0e07677d2db0f9e7d287baf4bb6b3069a9abe5044face0d87c8ec41","walletconflicts":[],"time":1471937712,"timereceived":1471937712,"bip125-replaceable":"no"}],"error":null,"id":null}

curl --url "http://127.0.0.1:8332" --data-binary '{"jsonrpc": "1.0", "method": "gettransaction", "params": ["8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c"] }' 

output
{"result":{"amount":0.00010000,"confirmations":53,"blockhash":"000000000000000000ad1278df428f8a01a6f4fb0c06ce6a9cdcaf12e164973e","blockindex":1729,"blocktime":1471938431,"txid":"8f70095662b39a5813039668e3b846669a9c52ef351a18f92b97f0572505a68c","walletconflicts":[],"time":1471937620,"timereceived":1471937620,"bip125-replaceable":"no","details":[{"account":"","address":"1G7GjuQx3krot5LYkphcXM4mhnmXi8Er9U"**,"category":"receive","amount":0.00010000**,"label":"","vout":0}],"hex":"01000000012bc52029f0dc260b8885a4b614a9c28cfff9e975808fa3b09e1bc6f0f507a795010000006a47304402200a21a6ba6c835fc425cdb282b1f35ada5fb3913de05a892fd1c2724e98a7c1490220676e915af65829f9d0c6abb2f0c2242b7c149c097cdfd7d2c7c57318ef0e87f301210261d7d5a53832dab69a3f869511071197c700aae62bafd965b9123ffdfb16eff9ffffffff0210270000000000001976a914a5b985795647ae4e0215054149eb03cd27b7671f88aca2ea0e00000000001976a91477b906930f44cacbc0216c1cb24400aefe06410f88ac00000000"},"error":null,"id":null}

corresponding iguana curls
curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"listtransactions\",\"account\":\"test\"}"

output
{"result":[{"account":"test","address":"RJfVbb1sGagbE2SeEZPiEzCC2Z49H9ufmp","txid":"a9677b86b5d923ec716d2af5616409c5dbfc9c36ecd89494f3668f1b97fa1c9a","vout":1}],"tag":"7555079936761262211"}

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"gettransaction\",\"txid\":\"a9677b86b5d923ec716d2af5616409c5dbfc9c36ecd89494f3668f1b97fa1c9a\"}"

output
{"version":1,"timestamp":1471262831,"vin":[{"sequence":4294967295,"txid":"4c6e2eb085dd42d254d89dc7ce7e016ac2889a0154ca25f4ce1a96360f8598c3","vout":0,"scriptSig":{"hex":"483045022100e8e5ad513f206efc93527d9528901998b714b81e44598d46911f0f3b88a6c35a022079f6ab0a85bf4c974af4e23466eda8956704b2449f18af6756b53125fb28a33c012102fd65f8abafff937b241f4be2c0bfb8543fbf3b1f801183963946e7bda74d9e88","asm":"3045022100e8e5ad513f206efc93527d9528901998b714b81e44598d46911f0f3b88a6c35a022079f6ab0a85bf4c974af4e23466eda8956704b2449f18af6756b53125fb28a33c01 02fd65f8abafff937b241f4be2c0bfb8543fbf3b1f801183963946e7bda74d9e88"}}],"numvins":1,"vout":[{"satoshis":"13886500000","value":138.86500000,"n":0,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 bf206345784bc9e7d0a45f4946a3aec40d23852a OP_EQUALVERIFY OP_CHECKSIG // RShmwVqW4hP3o9qz4hUa8zxyevw5pgPvtt","reqSigs":1,"type":"pubkeyhash","addresses":["RShmwVqW4hP3o9qz4hUa8zxyevw5pgPvtt"],"hex":"76a914bf206345784bc9e7d0a45f4946a3aec40d23852a88ac"}}, {"satoshis":"200000000","value":2,"n":1,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 66f0e82a46b67890c6fcc6c49ebcd8f149a81e66 OP_EQUALVERIFY OP_CHECKSIG // RJfVbb1sGagbE2SeEZPiEzCC2Z49H9ufmp","reqSigs":1,"type":"pubkeyhash","addresses":["RJfVbb1sGagbE2SeEZPiEzCC2Z49H9ufmp"],"hex":"76a91466f0e82a46b67890c6fcc6c49ebcd8f149a81e6688ac"}}],"numvouts":2,"locktime":0,"size":230,"txid":"a9677b86b5d923ec716d2af5616409c5dbfc9c36ecd89494f3668f1b97fa1c9a","blockhash":"1b183235a943e552a80912e5bf47f18cffe21db4a78a098518dd641bdf91bf93","blocktime":1471262970,"height":1244763,"confirmations":11736,"tag":"3190851954883357068"}

**Comment by pbca26** [comment]
listtransactions also is missing timestamp field
it's needed to sort txs w/o need to call gettransaction method

**Comment by jl777** [comment]
https://github.com/jl777/SuperNET/commit/5522459bfa7c8e42c333f4a9c99e8d58ad7eda22
https://github.com/jl777/SuperNET/commit/e02213f6189d44b2f5d25e60f7c3b6f41d5117b4 hopefully fixes this

**Comment by jl777** [comment]
is this fixed now?

**Comment by pbca26** [comment]
not quite
1) listtransactions is still missing tx amount and tx time
2) gettransaction is missing category and tx amount

**Comment by pbca26** [comment]
i think it's all good now
you can close this issue
